package kr.co.seoultel.message.mt.mms.direct.domain.protocol;

public class KtfProtocol {

    public static final String SUBMIT_REQ = "SubmitReq";
    public static final String SUBMIT_RES = "SubmitRsp";
    public static final String DELIVERY_REPORT_REQ = "DeliveryReportReq";
    public static final String DELIVERY_REPORT_RES = "DeliveryReportRsp";
    public static final String READ_REPLY_REQ = "ReadReplyReq";
    public static final String READ_REPLY_RES = "ReadReplyRsp";
    public static final String RS_ERROR_RES = "RSErrorRsp";
    public static final String VASP_ERROR_RES = "VaspErrorRsp";

    public static final String ECHO_REQ = "EchoReq";
    public static final String ECHO_RES = "EchoRsp";


    public static final String KTF_SUBMIT_ACK_SUCCESS_RESULT = "1000";                            //  성공
    public static final String KTF_SUBMIT_ACK_CLIENT_ERROR_RESULT = "2000";                       //  클라이언트 오류
    public static final String KTF_SUBMIT_ACK_MESSAGE_FORMAT_ERROR_RESULT = "2100";               //  메시지 포맷 오류
    public static final String KTF_SUBMIT_ACK_SOAP_ERROR_RESULT = "2101";                         //  SOAP Part 오류
    public static final String KTF_SUBMIT_ACK_SOAP_PARSING_ERROR_RESULT = "2102";                 //  SOAP 포맷 오류
    public static final String KTF_SUBMIT_ACK_SOAP_NOTSUPPORTED_METHOD_RESULT = "2103";           //  SOAP에서 미지원 method(MessageType) 오류
    public static final String KTF_SUBMIT_ACK_SOAP_VERSION_ERROR_RESULT = "2104";                 //  SOAP Element 중 Version 정보 오류
    public static final String KTF_SUBMIT_ACK_SOAP_MESSAGECLASS_ERROR_RESULT = "2105";            //  SOAP Element 중 Message Class 정보 오류
    public static final String KTF_SUBMIT_ACK_SOAP_SENDINFO_ERROR_RESULT = "2106";                //  SOAP Element인 SenderInfo 정보 오류
    public static final String KTF_SUBMIT_ACK_SOAP_RCPTINFO_ERROR_RESULT = "2107";                //  SOAP Element인 Recipients 정보 오류
    public static final String KTF_SUBMIT_ACK_SOAP_HUBID_ERROR_RESULT = "2108";                   //  SOAP Element인 VASPID(HUBSP) 정보 오류
    public static final String KTF_SUBMIT_ACK_SOAP_VASID_ERROR_RESULT = "2109";                   //  SOAP Element인 VASID(SUBCP) 정보 오류
    public static final String KTF_SUBMIT_ACK_SOAP_CALLBACK_ERROR_RESULT = "2110";                //  SOAP Element인 CallbackAddress 정보 오류
    public static final String KTF_SUBMIT_ACK_SOAP_SENDER_ERROR_RESULT = "2111";                  //  SOAP Element인 Sender 정보 오류
    public static final String KTF_SUBMIT_ACK_SOAP_TIMESTAMP_ERROR_RESULT = "2112";               //  SOAP Element인 StampTime 정보 오류
    public static final String KTF_SUBMIT_ACK_SOAP_SUBJECT_ERROR_RESULT = "2113";                 //  SOAP Element인 Subject 정보 오류
    public static final String KTF_SUBMIT_ACK_SOAP_TRANSACTIONID_ERROR_RESULT = "2114";           //  SOAP Element 중 Transaction ID 정보 오류
    public static final String KTF_SUBMIT_ACK_SOAP_MESSAGEID_ERRO_RESULT = "2115";                //  SOAP Element 중 Message ID 정보 오류
    public static final String KTF_SUBMIT_ACK_SOAP_SERVICETYPE_ERROR_RESULT = "2116";             //  SOAP Element 중 MessageType 정보 오류
    public static final String KTF_SUBMIT_ACK_MIME_ERROR_RESULT = "2150";                         //  Mime 메시지 포맷 오류
    public static final String KTF_SUBMIT_ACK_BOUNDARY_ERROR_RESULT = "2151";                     //  Bounday 오류
    public static final String KTF_SUBMIT_ACK_CONTENTTYPE_ERROR_RESULT = "2152";                  //  Content-Type 오류
    public static final String KTF_SUBMIT_ACK_CONTENT_EMPTY_RESULT = "2154";                      //  Content 오류
    public static final String KTF_SUBMIT_ACK_ENCODING_ERROR_RESULT = "2155";                     //  Content Encoding 오류
    public static final String KTF_SUBMIT_ACK_CONTENT_NOTSUPPORTED_RESULT = "2160";               //  지원하지 않는 Content 오류
    public static final String KTF_SUBMIT_ACK_CONTENT_CONVERSION_NOTSUPPORTED_RESULT = "2161";    //  변환을 지원하지 않는 Content 오류 수신단말이 지원할 수 없는  Content 포함이 된 경우 발생
    public static final String KTF_SUBMIT_ACK_CONTENTID_ERROR_RESULT = "2162";                    //  Content ID 오류
    public static final String KTF_SUBMIT_ACK_TRANID_DUPLICATE_ERROR_RESULT = "2163";             //  TRANSACTION ID가 중복
    public static final String KTF_SUBMIT_ACK_SERVER_ERROR_RESULT = "3000";                       //  서버 오류
    public static final String KTF_SUBMIT_ACK_SERVICE_ERROR_RESULT = "4000";                      //  서비스 오류
    public static final String KTF_SUBMIT_ACK_SERVICE_DENIED_RESULT = "4001";                     //  서비스 거부
    public static final String KTF_SUBMIT_ACK_HUB_AUTH_ERROR_RESULT = "4100";                     //  HUBSP 인증 오류
    public static final String KTF_SUBMIT_ACK_HUB_NOTFOUND_RESULT = "4101";                       //  HUBSP 없음 오류
    public static final String KTF_SUBMIT_ACK_HUB_BLOCK_RESULT = "4102";                          //  HUBSP 정지 오류
    public static final String KTF_SUBMIT_ACK_HUB_EXPIRED_RESULT = "4103";                        //  HUBSP 폐기 오류
    public static final String KTF_SUBMIT_ACK_HUB_IP_INVALID_RESULT = "4104";                     //  HUBSP IP 오류
    public static final String KTF_SUBMIT_ACK_HUB_CALLBACK_INVALID_RESULT = "4105";               //  HUBSP 회신번호 오류 (안심메시지)
    public static final String KTF_SUBMIT_ACK_RCPTCNT_OVER_RESULT = "4201";                       //  동보 전송 건수 초과 오류
    public static final String KTF_SUBMIT_ACK_HUB_OVER_INTRAFFIC_RESULT = "4202";                 //  허용 트래픽 초과 오류
    public static final String KTF_SUBMIT_ACK_HUB_OVER_MESSAGE_RESULT = "4203";                   //  SIZE 허용 메시지 SIZE 초과 오류
    public static final String KTF_SUBMIT_ACK_SPAM_ERROR_RESULT = "4400";                         //  스팸 처리 오류
    public static final String KTF_SUBMIT_ACK_SPAM_SUBJECT_RESULT = "4401";                       //  제목 스팸 처리 오류
    public static final String KTF_SUBMIT_ACK_SPAM_FILENAME_RESULT = "4402";                      //  파일명 스팸 처리 오류
    public static final String KTF_SUBMIT_ACK_SPAM_SUBCP_RESULT = "4403";                         //  SUB CP 스팸 처리 오류
    public static final String KTF_SUBMIT_ACK_UNDEFINED_RESULT = "9999";                          //  알 수 없는 에러



    public static final String KTF_REPORT_SUCCESS = "1000";
    public static final String KTF_REPORT_SUCCESS_SPAM = "1001";
    public static final String KTF_REPORT_SUCCESS_ANSIM = "1002";
    public static final String KTF_REPORT_CLIENT_ERROR = "2000";
    public static final String KTF_REPORT_MESSAGE_FORMAT_ERROR = "2100";
    public static final String KTF_REPORT_SOAP_ERROR = "2101";
    public static final String KTF_REPORT_SOAP_PARSING_ERROR = "2102";
    public static final String KTF_REPORT_SOAP_NOTSUPPORTED_METHOD = "2103";
    public static final String KTF_REPORT_SOAP_VERSION_ERROR = "2104";
    public static final String KTF_REPORT_SOAP_MESSAGECLASS_ERROR = "2105";
    public static final String KTF_REPORT_SOAP_SENDINFO_ERROR = "2106";
    public static final String KTF_REPORT_SOAP_RCPTINFO_ERROR = "2107";
    public static final String KTF_REPORT_SOAP_HUBID_ERROR = "2108";
    public static final String KTF_REPORT_SOAP_VASID_ERROR = "2109";
    public static final String KTF_REPORT_SOAP_CALLBACK_ERROR = "2110";
    public static final String KTF_REPORT_SOAP_SENDER_ERROR = "2111";
    public static final String KTF_REPORT_SOAP_TIMESTAMP_ERROR = "2112";
    public static final String KTF_REPORT_SOAP_SUBJECT_ERROR = "2113";
    public static final String KTF_REPORT_SOAP_TRANSACTIONID_ERROR = "2114";
    public static final String KTF_REPORT_SOAP_MESSAGEID_ERROR = "2115";
    public static final String KTF_REPORT_SOAP_SERVICETYPE_ERROR = "2116";
    public static final String KTF_REPORT_MIME_ERROR = "2150";
    public static final String KTF_REPORT_BOUNDARY_ERROR = "2151";
    public static final String KTF_REPORT_CONTENTTYPE_ERROR = "2152";
    public static final String KTF_REPORT_CONTENT_EMPTY = "2154";
    public static final String KTF_REPORT_ENCODING_ERROR = "2155";
    public static final String KTF_REPORT_CONTENT_NOTSUPPORTED = "2160";
    public static final String KTF_REPORT_CONTENT_CONVERSION_NOT = "2161";
    public static final String KTF_REPORT_CONTENTID_ERROR = "2162";
    public static final String KTF_REPORT_TRANID_DUPLICATE_ERROR = "2163";
    public static final String KTF_REPORT_RESELLERCODE_ERROR = "2200";
    public static final String KTF_REPORT_SERVER_ERROR = "3000";
    public static final String KTF_REPORT_LMSC_NETWORK_PROBLEM = "3400";
    public static final String KTF_REPORT_LMSC_NO_HEADER = "3505";
    public static final String KTF_REPORT_SERVICE_ERROR = "4000";
    public static final String KTF_REPORT_SERVICE_DENIED = "4001";
    public static final String KTF_REPORT_HUB_AUTH_ERROR = "4100";
    public static final String KTF_REPORT_HUB_NOTFOUND = "4101";
    public static final String KTF_REPORT_HUB_BLOCK = "4102";
    public static final String KTF_REPORT_HUB_EXPIRED = "4103";
    public static final String KTF_REPORT_HUB_IP_INVALID = "4104";
    public static final String KTF_REPORT_SERVICE_LIMIT = "4200";
    public static final String KTF_REPORT_RCPTCNT_OVER = "4201";
    public static final String KTF_REPORT_HUB_OVER_INTRAFFIC = "4202";
    public static final String KTF_REPORT_HUB_OVER_MESSAGESIZE = "4203";
    public static final String KTF_REPORT_SUBS_ERROR = "4300";
    public static final String KTF_REPORT_SUBS_INVALID = "4301";
    public static final String KTF_REPORT_SUBS_PORTED_SKT = "4302";
    public static final String KTF_REPORT_SUBS_PORTED_LGT = "4303";
    public static final String KTF_REPORT_SUBS_ADULT_AUTH_FAIL = "4304";
    public static final String KTF_REPORT_SUBS_MMS_NOTSUPPORTED = "4305";
    public static final String KTF_REPORT_SUBS_DUPLICATION = "4306";
    public static final String KTF_REPORT_SUBS_BLOCK = "4307";
    public static final String KTF_REPORT_SPAM_ERROR = "4400";
    public static final String KTF_REPORT_SPAM_SUBJECT = "4401";
    public static final String KTF_REPORT_SPAM_FILENAME = "4402";
    public static final String KTF_REPORT_SPAM_SUBCP = "4403";
    public static final String KTF_REPORT_SPAM_CALLBACK = "4404";
    public static final String KTF_REPORT_LMSCDR_UNDEFINED = "5200";
    public static final String KTF_REPORT_LMCSDR_TERMINAL_ERROR = "5300";
    public static final String KTF_REPORT_LMSCDR_TERMINAL_OUT_OF_MESSAGE_SIZE = "5310";
    public static final String KTF_REPORT_LMSCDR_TERMINAL_OUT_OF_MEMORY = "5320";
    public static final String KTF_REPORT_LMSCDR_PULL_OUTOFTIME = "5330";
    public static final String KTF_REPORT_LMSCDR_SEND_AUTH_FAIL = "5401";
    public static final String KTF_REPORT_LMSCDR_SEND_OUT_OF_MAX_RETRY_MAX = "5403";
    public static final String KTF_REPORT_LMSCDR_SEND_SENDER_BLOCK = "5409";
    public static final String KTF_REPORT_LMSC_MESSAGE_FORMAT_ERROR = "3430";
    public static final String KTF_REPORT_MMSC_NETWORK_PROBLEM = "7400";
    public static final String KTF_REPORT_MMSC_NO_HEADER = "7505";
    public static final String KTF_REPORT_MMSCDR_UNDEFINED_MMSC = "8200";
    public static final String KTF_REPORT_MMCSDR_TERMINAL_ERROR = "8300";
    public static final String KTF_REPORT_MMSCDR_TERMINAL_OUT_OF_MESSAGE_SIZE = "8310";
    public static final String KTF_REPORT_MMSCDR_TERMINAL_OUT_OF_MEMORY = "8320";
    public static final String KTF_REPORT_MMSCDR_PULL_OUTOFTIME = "8330";
    public static final String KTF_REPORT_MMSCDR_SEND_AUTH_FAIL = "8401";
    public static final String KTF_REPORT_MMSCDR_SEND_OUT_OF_MAX_RETRY_MAX = "8403";
    public static final String KTF_REPORT_MMSCDR_SEND_SENDER_BLOCK = "8408";
    public static final String KTF_REPORT_UNDEFINED = "9999";
}
