server:
  port: 11001


spring:
  application:
    name: KTF-SERVER


direct:
  telecom: KTF

  cpids:
    - cpid: "1528801080"
      max-tps: 10
      report-url: http://localhost:11000
    - cpid: "1528801081"
      max-tps: 15
      report-url: http://localhost:11000
    - cpid: "1528801082"
      max-tps: 7
      report-url: http://localhost:11000
    - cpid: "1528801083"
      max-tps: 20
      report-url: http://localhost:11000
    - cpid: "1528801084"
      max-tps: 13
      report-url: http://localhost:11000


storage:
  history:
    file-path: /Users/bak.libra26/MCMP/kr.co.seoultel.message.mt.mms-direct-dummy/src/main/resources/storage/ktf/history.storage

  report:
    file-path: /Users/bak.libra26/MCMP/kr.co.seoultel.message.mt.mms-direct-dummy/src/main/resources/storage/ktf/report.storage
